name: reactivity
description: "A powerful reactivity system for Flutter, inspired by Vue 3's @vue/reactivity."
version: 0.0.1
homepage: "https://github.com/tachibana-shin/flutter-reactivity"

environment:
  sdk: ^3.6.2
  flutter: '>=3.3.0'

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  notifier_plus: ^0.1.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

